#!/usr/bin/env bash

if [ "$FLASK_ENV" = "development" ] || [ "$FLASK_ENV" = "testing" ]
then  
  watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery worker -B -l info -A app.tasks -n scheduler-worker -s /tmp/celerybeat-schedule
else  
  celery worker -B -l info -A app.tasks -n scheduler-worker -s /tmp/celerybeat-schedule
fi