#!/usr/bin/env bash

if [ "$FLASK_ENV" = "development" ] || [ "$FLASK_ENV" = "testing" ]
then
  python3 -m flask run --host=0.0.0.0 --port=$FLASK_PORT  
else
  waitress-serve --port=$FLASK_PORT --call 'app:create_app' 
fi
